project:
  type: website

website:
  title: "brdrQ - Aligning borders with QGIS"
  navbar:
    logo: "static/logo.svg"
    left:
      - text: Home
        href: index.qmd
      - text: FeatureAligner
        href: featurealigner.md
      - text: Autocorrectborders (BULK)
        href: autocorrectborders.md
      - text: GRB Updater (BULK - Flanders specific)
        href: autoupdateborders.md
      - text: Q & A
        href: qa.qmd

lang: en

highlight-style: github-dark

format:
  html:
    theme:
      - static/custom.scss
    code-fold: false
    embed-resources: false
    toc: true
    toc-location: "right"